import Head from "next/head";
import styles from "../styles/HomePage.module.css";

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sleep Tracker</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Sleep Tracker!</h1>
      </main>
    </div>
  );
}
